### ISSUE TITLE
Installation w/o wget

### ISSUE THREAD

**Issue by kescobo** [applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics#188]
Trying to install according to [instructions from docs](http://readiab.org/book/latest/1/1#3)

Got the following message:

```
Linking packages ...
/Users/KBLaptop/miniconda3/envs/iab/bin/.iab-post-link.sh: line 1: wget: command not found
unzip:  cannot find or open IAB-notebooks.zip, IAB-notebooks.zip.zip or IAB-notebooks.zip.ZIP.
Error: Error: post-link failed for: iab-0.1.1-np19_0
```

Evidently OS X (I'm running 10.11.1) doesn't come with `wget` by default. Once I figured this out, it was simple enough to get `wget`with homebrew, but I also had to uninstall the failed `iab` environment. Not sure if there's a way to get around this, but for someone with a bit less comfort with the command line, this might be daunting (eg. this would have taken me a long time to figure out 6 months ago).

Was going to suggest using binder, but @jairideout beat me to it: #177

**Comment by gregcaporaso** [comment]
This change will happen as part of the next official release. Thanks for pointing it out @kescobo. In the meantime, we're going to be experimenting with using Binder.

**Comment by torreybyrd** [comment]
Brand-new to the command line, and having the same issue as kescobo when I try to install IAB. I got the following message:
`/Users/byrdv/miniconda3/envs/iab/bin/.iab-post-link.sh: line 1: wget: command not found
unzip:  cannot find or open IAB-notebooks.zip, IAB-notebooks.zip.zip or IAB-notebooks.zip.ZIP.
Error: Error: post-link failed for: http://conda.binstar.org/gregcaporaso::iab-0.1.1-np19_0
`

When I click the link to the Binder version of IAB, I get a "loading..." message for a while, and then it says "failed!" with no explanation of why or how to circumvent the problem. So, my questions are: 

1. How do I uninstall the failed IAB environment? 
2. How do I either (A) get wget so I can successfully re-install IAB, or (B) get Binder to work?

Thanks so much in advance for your help.

**Comment by corburn** [comment]
### Environment
OS X

### Instruction followed:

[1.1.3 Local Installation](http://readiab.org/book/latest/1/1#3)
```
conda create --name iab -c http://conda.binstar.org/gregcaporaso python=3.4 iab
```

### Error encountered:
```
# ./miniconda3/envs/iab/bin/.iab-post-link.sh: line 1: wget: command not found
```

I have not yet looked at the master branch, but here is an idea for the error encountered in IAB 0.1.1:
```
#!/bin/sh
# Download and extract IAB Notebook.
# Fallback to curl if wget fails.
URL=http://readIAB.org/book/0.1.1/IAB-notebooks.zip
{ wget -O - $URL || curl $URL; } | unzip
```

@torreybyrd 
1. How do I uninstall the failed IAB environment?
    ```
    conda remove --name iab --all
    ```
2. How do I either (A) get wget so I can successfully re-install IAB, ~~or (B) get Binder to work~~?
    ```
    # Install Homebrew package manager for macOSX http://brew.sh/
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install wget
    ```

**Comment by Adrianzo** [comment]
Apple users can install wget with homebrew.
Also, I believe that `wget` can be replaced by `curl` with minor adjustments.

**Comment by gregcaporaso** [comment]
@torreybyrd, did you get this sorted out?

**Comment by gregcaporaso** [comment]
Closing as the latest conda-based install instructions now include installation of `wget` for cases (like macOS) where it is not already installed.
