### ISSUE TITLE
Is there a way to Read Interactively on Windows?

### ISSUE THREAD

**Issue by NoamTene** [applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics#284]
I have anaconda installed on Windows but the instructions on http://readiab.org/ are for "OS X and Linux only".  

Apparently scikit-bio=0.4.2 is not available for Windows but I was able to install what seems like a later version of scikit-bio:

"""
The following NEW packages will be INSTALLED:
    cachecontrol: 0.12.5-py36_0
    lockfile:     0.12.2-py36h0468280_0
    scikit-bio:   0.5.2-py36_1          scw
The following packages will be DOWNGRADED:
    numpy:        1.14.5-py36h9fa60d3_4     --> 1.13.3-py36h5c71026_4
'''"

Can you tell me if there is a way to proceed so I can Read IAB Interactively?
Also can you tell me why it downgraded numpy?

Thanks,

**Comment by gregcaporaso** [comment]
@NoamTene, at present we don't have a way to support reading IAB interactively with the code running locally on Windows, but we are experimenting with <a href="https://mybinder.org">Binder 2.0</a> to provide cross-platform support where the notebooks would run remotely. We're still experiencing some difficulties getting the _Phylogenetic reconstruction_ chapter to run correctly, but all of the others work now. You can test this out at [this link](https://mybinder.org/v2/gh/caporaso-lab/built-iab/master?filepath=IAB-notebooks%2Findex.ipynb), and I'll be interested to hear whether this works for you, and if not, what problems you experience. This should work on Windows (in addition to other platforms). This Binder link will be going up to https://readIAB.org shortly, and I'll update this post when that goes live. 

The reason that numpy was downgrade in this process is that scikit-bio is restrictive of the versions of its dependencies. This is something that the scikit-bio team (which I am a part of) may be trying to remedy in the future.

**Comment by gregcaporaso** [comment]
@NoamTene, we have tested Binder 2.0 and all chapters now work, so this is your best option for reading IAB interactively on Windows. You can use this by following [this link](https://mybinder.org/v2/gh/applied-bioinformatics/built-iab/master). Hope this helps!
