### ISSUE TITLE
link to "one of most cited articles in modern biology" broken chap 2.1 para 1

### ISSUE THREAD

**Issue by cmatKhan** [applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics#316]
### Describe the environment
binder > jupyter lab
What version of IAB are you reading (e.g. v0.0.1)?
dev
```python

### Describe the problem
link broken
#### Steps to reproduce
click the link
  
#### Observed Results

  a sense of disappointment
  
#### Expected Results

  great things

**Comment by ebolyen** [comment]
Thanks for the report @cmatKhan!

I believe that link was supposed to reference BLAST:
https://scholar.google.com/scholar?q=basic+local+alignment+search+tool

@gregcaporaso, it looks like you set up a custom view for this, how would you like to proceed there?

**Comment by gregcaporaso** [comment]
Oops, thanks for catching that @cmatKhan!

I think I'll address this by pointing to PubMed rather than Google Scholar.
