### ISSUE TITLE
scikit currently requires numpy==1.8 (API version 9), release ipython comes with version 7?

### ISSUE THREAD

**Issue by 2grep** [applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics#64]
I updated ipython just before starting into iab, but found this as one of my first dependencies that needed addressing. Should these versions be pinned or maintained in requirements.py?

**Comment by gregcaporaso** [comment]
I believe this is no longer an issue, but please reopen if I'm wrong about that.
